-- 더미 데이터 생성하기
--INSERT INTO article(id, title, content) VALUES(1, '가가가가', '1111');
--INSERT INTO article(id, title, content) VALUES(2, '나나나나', '2222');
--INSERT INTO article(id, title, content) VALUES(3, '다다다다', '3333');
--INSERT INTO article(title, content) VALUES('가가가가', '1111');
--INSERT INTO article(title, content) VALUES('나나나나', '2222');
--INSERT INTO article(title, content) VALUES('다다다다', '3333');
--
--INSERT INTO article(title, content) VALUES('당신의 인생 영화는', '댓글 고');
--INSERT INTO article(title, content) VALUES('당신의 소울 푸드는', '댓글 고고');
--INSERT INTO article(title, content) VALUES('당신의 취미는', '댓글 고고고');

--INSERT INTO comment(article_id, nickname, body) VALUES(4, 'Park', '굿 윌 헌팅');
--INSERT INTO comment(article_id, nickname, body) VALUES(4, 'Kim', '아이 엠 샘');
--INSERT INTO comment(article_id, nickname, body) VALUES(4, 'Choi', '쇼생크 탈출');
--
--INSERT INTO comment(article_id, nickname, body) VALUES(5, 'Park', '치킨');
--INSERT INTO comment(article_id, nickname, body) VALUES(5, 'Kim', '샤브샤브');
--INSERT INTO comment(article_id, nickname, body) VALUES(5, 'Choi', '초밥');
--
--INSERT INTO comment(article_id, nickname, body) VALUES(6, 'Park', '조깅');
--INSERT INTO comment(article_id, nickname, body) VALUES(6, 'Kim', '유투브 시청');
--INSERT INTO comment(article_id, nickname, body) VALUES(6, 'Choi', '독서');

--INSERT INTO pizza(name, price) VALUES('페퍼로니 피자', '25,900');
--INSERT INTO pizza(name, price) VALUES('불고기 피자', '29,900');
--INSERT INTO pizza(name, price) VALUES('고구마 피자', '30,900');
--INSERT INTO pizza(name, price) VALUES('포테이토 피자', '27,900');
--INSERT INTO pizza(name, price) VALUES('치즈 피자', '23,900');

--INSERT INTO group_entity(name) VALUES('Group H');
--
--INSERT INTO team_entity(group_entity_id, name) VALUES(1, 'Portugal');
--INSERT INTO team_entity(group_entity_id, name) VALUES(1, 'Ghana');
--INSERT INTO team_entity(group_entity_id, name) VALUES(1, 'Uruguay');
--INSERT INTO team_entity(group_entity_id, name) VALUES(1, 'Korea Republic');

--INSERT INTO coffee(name, price) VALUES('아메리카노', '4500');
--INSERT INTO coffee(name, price) VALUES('라떼', '5000');
--INSERT INTO coffee(name, price) VALUES('카페 모카', '5500');
-- ctrl + / : 주석처리

--INSERT INTO reply(article_id, nickname, body) VALUES(4, 'Park', '굿 윌 헌팅');
--INSERT INTO reply(article_id, nickname, body) VALUES(4, 'Kim', '아이 엠 샘');
--INSERT INTO reply(article_id, nickname, body) VALUES(4, 'Choi', '쇼생크 탈출');
--
--INSERT INTO reply(article_id, nickname, body) VALUES(5, 'Park', '치킨');
--INSERT INTO reply(article_id, nickname, body) VALUES(5, 'Kim', '샤브샤브');
--INSERT INTO reply(article_id, nickname, body) VALUES(5, 'Choi', '초밥');
--
--INSERT INTO reply(article_id, nickname, body) VALUES(6, 'Park', '조깅');
--INSERT INTO reply(article_id, nickname, body) VALUES(6, 'Kim', '유투브 시청');
--INSERT INTO reply(article_id, nickname, body) VALUES(6, 'Choi', '독서');