# yml 문법(properties보다 가독성이 좋고 편리한 기능을 제공)
# 1. key: value로 이루어짐.
# 2. hiarachy를 표현할 때는 들여쓰기로 표현(2칸)
# 3. application.yml과 application.properties는 같이 사용할 수 없음
#     -> 만약에 2개의 파일이 동시에 있다면 우선순위는 application.properties가 높음
server:
  port: 9000  # server.port=9000
  servlet:
    encoding:
      force: true # server.servlet.encoding.force=true




spring:
  # jsp파일을 찾을 때 사용하는 경로
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  sql:
    init:
      mode: always

  application:
    name: firstproject

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

          naver:
            client-id:
            client-secret:
            scope:
              - name
              - email
              - profile_image
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9000/login/oauth2/code/naver

          kakao:
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id




#  h2:
#    console:
#      enabled: true

#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:orcl
#    username: boarduser1
#    password: 1234




logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE